---

- hosts: all
  become: true
  tasks: 
  
  - name: install apache and php packages for CentOS host
    yum:
      name: 
         - httpd
         - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

  - name: install apache and php package for Ubuntu host
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
