---

- hosts: all
  become: true
  tasks:
  - name: create user simone
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2FgY+UXqfS3FtzzPk2tI0p+blTtbVS91V340SxjDQA Ansible default"

  - name: add sudoers file for simone
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root

  - name: install zip, unzip tools for files extraction
    yum:
      name:
         - zip
         - unzip
      state: latest
      update_cache: yes 
