---

- hosts: all
  become: true
  tasks: 
  
  - name: remove apache on all CentOS host
    yum:
      name: 
         - httpd
         - php
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: remove php on all host
    apt:
      name: 
         - apache2
         - libapache-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"
