---

- hosts: all
  become: true
  tasks:
  
  - name: install updates (CentOS)
    tags: always
    yum:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache and php on centos server
    tags: apache,centOS,httpd
    yum: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,centOS,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_server
  become: true
  tasks:

  - name: install sql server on CentOS server 
    tags: db,mariadb
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_server
  become: true
  tasks:

  - name: Install file server on CentOS server
    tags: samba
    yum:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install unzip
    package:
       name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.2/terraform_1.3.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
