- name: install web apache server on (CentOS)
  tags: apache,httpd,centos 
  yum:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"

- name: install web apache server on (Ubuntu)
  tags: apache,httpd,ubuntu
  apt:
    name: 
       - apache2
       - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start service on Centos host
  service:
    name: httpd
    state: restarted
    
- name: copy file for site
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
